/* moves.mjs — what moves you inside a class, and what the moves must reach.
 *
 * Copyright (c) 2026 Carles Marin. All rights reserved.
 * Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
 *
 * Part IX-B's question, made walkable.  Two boundary conditions are the same theory exactly when
 * every cone reads the same local datum, so a MOVE is a swap of letters that changes neither: it
 * is an element of the relation lattice.  Its DEGREE is how much weight it carries across,
 * sum over the positive part of n_i w_i, which equals the negative part because the weights
 * balance.
 *
 * WHY THE DEGREE IS THE POINT, and not a technicality.  Sturmfels and Sullivant prove that a graph
 * with a K_4 minor has a minimal generator of degree four in its cut ideal, and Engstrom proved
 * their converse: the cut ideal is generated by quadrics if and only if the graph is K_4-minor
 * free.  So whether the degree-two moves alone connect a fibre, or leave it in pieces that only
 * degree four closes, is that theorem applied to the graph the orbifold defines.  A section can
 * show it by counting components as the degree allowed goes up, and someone proposing a move set
 * can find out in one click that theirs is not enough.
 *
 * AND IT CROSS-CHECKS THE SERIES.  The Hilbert numerator already says what the relation degrees
 * are — (1-x^2)^3 for T^2/Z_2 is three relations of degree two — by a route that never looks at a
 * fibre.  The smallest degree that connects every fibre must be the largest of those.  Two
 * independent computations of the same fact, which is the standard here.
 *
 * SCOPE, and it is the paper's own.  Everything here is derived for a CYCLIC point group,
 * Gamma = Lambda x| Z_m.  The product orbifold (S^1/Z_2)^k is not of that form: its orbit space is
 * a rectangle with mirror edges rather than a sphere with cone points, and §8 leaves orbifolds with
 * mirror boundary open.  Its alphabet and its sixteen moves are a NAMED case with supplied data,
 * never something this file derives, and a section showing it has to say which of the two it is
 * looking at.
 *
 * D3: pure functions, no DOM.
 */
import { conePoints, multisets, realForm } from "./alphabet.mjs";

/* Every boundary condition of rank N, as a multiplicity vector over the letters, together with the
 * class it falls in.  Returns a Map from the datum's key to the list of conditions in it. */
export function fibres(A, m, family, N) {
  const cones = conePoints(A, m);
  const letters = realForm(A, m, family);
  const ws = letters.map((L) => L.weight);
  const out = new Map();
  for (const pick of multisets(ws, N)) {
    const n = new Array(letters.length).fill(0);
    for (const [idx, mult] of pick) n[idx] = mult;
    const acc = cones.map((c) => new Array(c.order).fill(0));
    for (let i = 0; i < n.length; i++) {
      if (!n[i]) continue;
      for (let ci = 0; ci < cones.length; ci++)
        for (let k = 0; k < cones[ci].order; k++) acc[ci][k] += n[i] * letters[i].datum[ci][k];
    }
    const key = JSON.stringify(acc);
    if (!out.has(key)) out.set(key, { datum: acc, members: [] });
    out.get(key).members.push(n);
  }
  return { fibres: out, letters, ws, cones };
}

/* The degree of the move taking u to v: the weight carried across.  The two sides agree because a
 * move preserves the rank, so either may be read; they are compared here, and a disagreement is a
 * fault rather than a rounding — it would mean the two conditions are not of the same rank. */
export function moveDegree(u, v, ws) {
  let up = 0, down = 0;
  for (let i = 0; i < u.length; i++) {
    const d = u[i] - v[i];
    if (d > 0) up += d * ws[i]; else down += -d * ws[i];
  }
  if (up !== down) throw new Error("a move between conditions of different rank: " + up + "/" + down);
  return up;
}

/* The connected components of one fibre under moves of degree at most `maxDeg`.
 * Returns { components, sizes, degrees } — `degrees` is the multiset of degrees actually used,
 * which is what tells you whether the bound was reached or merely allowed. */
export function fibreComponents(members, ws, maxDeg) {
  const n = members.length;
  const parent = Array.from({ length: n }, (_, i) => i);
  const find = (i) => { while (parent[i] !== i) { parent[i] = parent[parent[i]]; i = parent[i]; } return i; };
  const used = new Map();
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++) {
      const d = moveDegree(members[i], members[j], ws);
      if (d > maxDeg) continue;
      used.set(d, (used.get(d) || 0) + 1);
      const a = find(i), b = find(j);
      if (a !== b) parent[a] = b;
    }
  const roots = new Map();
  for (let i = 0; i < n; i++) {
    const r = find(i);
    roots.set(r, (roots.get(r) || 0) + 1);
  }
  return { components: roots.size, sizes: [...roots.values()].sort((a, b) => b - a),
           degrees: [...used.entries()].sort((a, b) => a[0] - b[0]) };
}

/* The smallest degree at which EVERY fibre of rank N is connected.
 *
 * This is the number the series predicts: the largest relation degree in the Hilbert numerator.
 * Returns null when no degree up to `cap` does it, which is an answer and not a failure — but it
 * must be reported as "not reached below cap" and never as a number. */
export function connectingDegree(A, m, family, N, cap = 12) {
  const { fibres: fs, ws } = fibres(A, m, family, N);
  for (let d = 1; d <= cap; d++) {
    let all = true;
    for (const f of fs.values())
      if (fibreComponents(f.members, ws, d).components !== 1) { all = false; break; }
    if (all) return d;
  }
  return null;
}

/* The relation degrees the SERIES says there are, read off a Hilbert numerator: a factor
 * (1 - x^d)^k contributes k relations of degree d.  Read as the multiset of degrees at which the
 * numerator has a sign change, which is enough for the products of cyclotomic-type factors these
 * cases produce and is honest about being a reading rather than a factorisation. */
export function relationDegreesFromNumerator(P) {
  const out = [];
  for (let i = 1; i < P.length; i++) if (P[i] !== 0) out.push({ degree: i, coefficient: P[i] });
  return out;
}
