import {readFileSync} from 'node:fs';
import {nrModel} from './src/modules/neutrino_ring.mjs';
import {ndDefaults,ndValidate,ndWeakWidths,ndCoherence,ndFlight,ndModel,ndSummary,ND_CONSTANTS} from './src/modules/neutrino_decay.mjs';
import {EXPERIMENT} from './src/kernel/experiment.mjs';
let passed=0,failed=0;
const check=(name,ok)=>{if(ok)passed++;else{failed++;console.error('FAIL '+name);}};
const near=(a,b,tol=2e-11)=>Number.isFinite(a)&&Math.abs(a-Number(b))<=tol*Math.max(1e-100,Math.abs(Number(b)));
const throws=f=>{try{f();return false;}catch{return true;}};
const refs=JSON.parse(readFileSync('data/neutrino_decay_reference.json','utf8'));
for(const p of refs.widths){const r=ndWeakWidths(+p.massGeV,+p.activeWeight,+p.lightActiveWeight,p.flavour);
  for(const k of ['W','Z','h'])check('75-digit '+p.flavour+' '+p.massGeV+' '+k,near(r.channelsEV[k],p.channelsEV[k],2e-10));
}
for(const p of refs.models){const r=ndModel(nrModel(p.input));
  p.rows.forEach((a,i)=>{for(const k of ['W','Z','h'])check('matrix spectrum width '+i+' '+k,near(r.rows[i].channelsEV[k],a.channelsEV[k]));
    check('proper lifetime '+i,a.tauSeconds===null?r.rows[i].flight.tauSeconds===null:near(r.rows[i].flight.tauSeconds,a.tauSeconds));
    check('proper distance '+i,a.ctauMM===null?r.rows[i].flight.ctauMM===null:near(r.rows[i].flight.ctauMM,a.ctauMM));
  });
}
for(const p of refs.coherence){const r=ndCoherence(+p.deltaOverGamma,1);
  check('time quadrature ratio '+p.deltaOverGamma,near(r.ssOverOS,p.ssOverOS));
  check('time quadrature fraction '+p.deltaOverGamma,near(r.ssFraction,p.ssFraction));
}
check('exact-SI hbar conversion',near(ND_CONSTANTS.hbarGeVs,refs.constants.hbarGeVs,2e-15));
const r=nrModel(),base=ndModel(r),extra=ndModel(r,{extraEV:base.selected.widthEV});
check('adding equal width halves proper lifetime',near(extra.selected.flight.tauSeconds,base.selected.flight.tauSeconds/2));
check('extra width suppresses ideal SS ratio',extra.selected.coherence.ssOverOS<base.selected.coherence.ssOverOS);
check('extra width does not move poles',extra.rows.every((p,i)=>p.centerGeV===base.rows[i].centerGeV&&p.splitEV===base.rows[i].splitEV));
check('all six fractions sum to one',extra.rows.every(p=>near(Object.values(p.channelFractions).reduce((a,b)=>a+b,0),1)));
check('neutral light residue retained',near(base.selected.weak.channelsEV.Z/ndWeakWidths(base.selected.centerGeV,base.selected.activeWeight,1).channelsEV.Z,1-r.deficit));
const high=ndWeakWidths(1e8,.01,1),frac=Object.fromEntries(Object.entries(high.channelsEV).map(([k,v])=>[k,v/high.sumEV]));
check('high-mass channel ratio 2:1:1',near(frac.W,.5,1e-10)&&near(frac.Z,.25,1e-10)&&near(frac.h,.25,1e-10));
const threshold=EXPERIMENT.m_W.value+EXPERIMENT.m_tau.value;
check('exact tau threshold closed',ndWeakWidths(threshold,.001,1,'tau').channelsEV.W===0);
check('tau threshold opens positively',ndWeakWidths(threshold+.001,.001,1,'tau').channelsEV.W>0);
check('below threshold is partial sum zero',ndWeakWidths(70,.01).sumEV===0);
check('neutral residue zero closes light Z and h',ndWeakWidths(300,.1,0).channelsEV.Z===0&&ndWeakWidths(300,.1,0).channelsEV.h===0);
check('Dirac limit has zero SS fraction',ndCoherence(0,1).ssOverOS===0&&ndCoherence(0,1).ssFraction===0);
check('resolved splitting approaches equal charge rates',ndCoherence(1e100,1e-100).ssOverOS===1);
check('large ratio remains numerically bounded',ndCoherence(1e200,1).ssOverOS===1);
check('overflowing splitting ratio is explicit',ndCoherence(1,1e-320).deltaOverGamma===null&&ndCoherence(1,1e-320).status.includes('floating-point'));
check('subnormal width preserves finite flight probability',ndFlight(1e-320).meanFlightMM===null&&ndFlight(1e-320).windowProbability>0);
const subnormal=ndModel(nrModel({calibrate:false,mDGeV:0}),{extraEV:1e-320});
check('extreme lifetime has safe explanatory summary',ndSummary(subnormal).includes('outside numerical range'));
check('zero included width is undefined',ndCoherence(1,0).ssOverOS===null&&ndFlight(0).ctauMM===null);
const zero=ndModel(nrModel({calibrate:false,mDGeV:0}));
check('no invented stability verdict',zero.rows.every(p=>p.widthEV===0&&p.flight.windowProbability===null)&&ndSummary(zero).includes('does not establish'));
const added=ndModel(nrModel({calibrate:false,mDGeV:0}),{extraEV:1});
check('zero weak mixing can have a chosen extra width',added.rows.every(p=>p.widthEV===1&&p.channelFractions.extra===1));
check('active production absence remains explicit',added.selected.issues.some(x=>x.includes('No active-current')));
check('higher-pair open cascades enumerated but not assigned a rate',base.rows[5].weakCascades.some(c=>c.Zopen)&&base.missing.some(x=>x.includes('cascades')));
check('full ring width remains unknown',base.status.includes('not evaluated')&&base.missing.some(x=>x.includes('Majoron')));
const f=ndFlight(1),boosted=ndFlight(1,10);
check('boost changes lab distance only',boosted.tauSeconds===f.tauSeconds&&near(boosted.meanFlightMM,10*f.meanFlightMM));
check('one mean length contains 1-exp(-1)',near(ndFlight(1,1,0,f.meanFlightMM).windowProbability,1-Math.exp(-1)));
const a=ndFlight(1,1,0,f.meanFlightMM),b=ndFlight(1,1,f.meanFlightMM,2*f.meanFlightMM),ab=ndFlight(1,1,0,2*f.meanFlightMM);
check('disjoint flight windows add',near(a.windowProbability+b.windowProbability,ab.windowProbability));
check('narrow window has nonzero probability',ndFlight(1e-12,1,1e-12,2e-12).windowProbability>0);
check('far window underflows to zero safely',ndFlight(1e9,1,1,2).windowProbability===0);
for(const p of [{pair:1.5},{pair:7},{extraEV:-1},{extraEV:NaN},{boost:0},{lminMM:1,lmaxMM:1},{lmaxMM:Infinity}])check('invalid input rejected '+JSON.stringify(p),throws(()=>ndValidate(p)));
for(const call of [()=>ndWeakWidths(0,.1),()=>ndWeakWidths(100,-.1),()=>ndWeakWidths(100,.1,2),()=>ndWeakWidths(100,.1,1,'all'),()=>ndCoherence(-1,1),()=>ndFlight(-1)])check('invalid physical arguments rejected',throws(call));
check('defaults valid',JSON.stringify(ndValidate())===JSON.stringify(ndDefaults()));
check('model export serializes all rows without NaN',!JSON.stringify(extra).includes('NaN')&&JSON.parse(JSON.stringify(extra)).rows.length===6);
console.log(`neutrino decay: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
