/* _test_blkt.mjs — the tower when the branes have mass, and the limit that says it is right.
 *
 * Copyright (c) 2026 Carles Marin. All rights reserved.
 * Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
 *
 * THE CONTROL THAT DECIDES IT is c -> 0.  Switch the localized term off and the roots of the
 * transcendental mass equation must collapse onto the ordinary twisted tower
 *
 *     x^2 = (n + m alpha_1 / 2)^2 + ((m alpha_2 + q)/2 + k)^2,
 *
 * which is written in closed form and comes from the POLES of the summand, not from this
 * module's root finder.  Two independent objects meeting is the check; a root finder agreeing
 * with itself is not.
 *
 * The special functions are checked against values that are not ours either: psi(1) = -gamma,
 * psi(1/2) = -gamma - 2 ln 2, E_1 at a tabulated point, and Gamma(-2, x) against its own
 * defining integral done numerically.
 *
 *   node _test_blkt.mjs
 */
import { readFileSync } from "node:fs";
import { digamma, expint1, gammaMinus2, blktTerm, blktSreg, blktMassEq, blktFreeTower,
         blktRoots, blktVsector, blktSector, blktApprox, blktApproxRoot, blktScaleFormula }
  from "./src/kernel/blkt.mjs";

let pass = 0, fail = 0;
const ok = (n, c, d = "") => { if (c) { pass++; console.log(`  ok   ${n}`); }
                               else { fail++; console.log(`  FAIL ${n}${d ? "  — " + d : ""}`); } };
const H = (s) => console.log(`\n${s}`);
const near = (a, b, t) => Math.abs(a - b) <= t;

const GAMMA = 0.5772156649015329;

/* ------------------------------------------------------------------ the special functions */

H("the special functions, against mpmath at 40 digits");
{
  /* WHY A FILE AND NOT A LITERAL.  The first version of this harness carried E_1(5) typed from
   * memory, and it was wrong in the 12th digit while the JS was right -- so the harness failed a
   * correct implementation.  A reference you wrote yourself is not a reference.  These come from
   * mpmath, generated by `build/make_blkt_reference.py` in the Sage image and archived. */
  const REF = JSON.parse(readFileSync(new URL("./tests/blkt_reference.json", import.meta.url), "utf8"));
  const rel = (got, want) => Math.abs(got / Number(want) - 1);

  for (const [z, want] of Object.entries(REF.digamma))
    ok(`psi(${z}) matches mpmath to 1e-13 relative`, rel(digamma(Number(z)), want) < 1e-13,
       `${digamma(Number(z))} vs ${want}`);
  for (const [x, want] of Object.entries(REF.e1))
    ok(`E_1(${x}) matches mpmath to 1e-13 relative`, rel(expint1(Number(x)), want) < 1e-13,
       `${expint1(Number(x))} vs ${want}`);
  for (const [x, want] of Object.entries(REF.gamma_minus2))
    ok(`Gamma(-2, ${x}) matches mpmath to 1e-12 relative`,
       rel(gammaMinus2(Number(x)), want) < 1e-12, `${gammaMinus2(Number(x))} vs ${want}`);

  /* the composite the potential actually evaluates, so the recurrence is checked where it is used */
  for (const [key, want] of Object.entries(REF.potential_integral)) {
    if (key === "note") continue;
    const [x, L] = key.split(",").map((p) => Number(p.split("=")[1]));
    const got = Math.pow(x, 4) * gammaMinus2(x * x / L);
    ok(`the (4.2) integrand at ${key} matches mpmath`, rel(got, want) < 1e-12, `${got} vs ${want}`);
  }

  /* two identities, which no table can be wrong about */
  ok("psi(z+1) = psi(z) + 1/z, at three places",
     [0.3, 2.7, 11.4].every((z) => Math.abs(digamma(z + 1) - digamma(z) - 1 / z) < 1e-11));
  ok("the two branches of E_1 agree where they meet",
     Math.abs(expint1(1 - 1e-9) - expint1(1 + 1e-9)) < 1e-8);
  ok("psi(z) - ln z is -1/(2z) to leading order, which is why (3.21) converges",
     Math.abs((digamma(5000) - Math.log(5000)) + 1 / 10000) < 1e-8);
}

/* ------------------------------------------------------------------ the summand */

H("the summand is the paper's, on both sides of its branch");
{
  const o = { m: 1, q: 0, alpha1: 0.4, alpha2: 0.3 };
  /* z > 0 and z < 0 are different formulae in their (3.17); the function they define is one
   * function, so it must be continuous where z crosses zero */
  const nAt = 0;
  const xc = Math.abs(nAt + o.m * o.alpha1 / 2);       /* z_0 = 0 exactly here */
  const below = blktTerm(xc - 1e-7, nAt, o.m, o.alpha1, o.alpha2, o.q);
  const above = blktTerm(xc + 1e-7, nAt, o.m, o.alpha1, o.alpha2, o.q);
  ok("the trigonometric and hyperbolic branches join continuously",
     near(below, above, 1e-4), `${below} vs ${above}`);
  ok("...and at the join it is the limit sin(a)/r -> 2 pi / (1 - cos)",
     near(blktTerm(xc, nAt, o.m, o.alpha1, o.alpha2, o.q),
          2 * Math.PI / (1 - Math.cos(Math.PI * (o.m * o.alpha2 + o.q))), 1e-9));

  ok("deep in the hyperbolic branch it does not overflow to NaN",
     Number.isFinite(blktTerm(0.01, 400, 1, 0.4, 0.3, 0)));
  ok("...and there it decays like 1/|n|, which is the divergence (3.21) subtracts",
     near(Math.abs(blktTerm(0.01, 300, 1, 0.4, 0.3, 0)) * 300, 1, 0.02),
     String(Math.abs(blktTerm(0.01, 300, 1, 0.4, 0.3, 0)) * 300));
}

H("the regularised sum converges, which is the whole point of the digammas");
{
  const o = { m: 1, q: 0, alpha1: 0.4, alpha2: 0.3 };
  const a = blktSreg(0.37, { ...o, N: 200 });
  const b = blktSreg(0.37, { ...o, N: 800 });
  const c = blktSreg(0.37, { ...o, N: 3200 });
  ok("it settles as N grows", near(a, b, 2e-3) && near(b, c, 6e-4),
     `N=200 ${a}, N=800 ${b}, N=3200 ${c}`);
  ok("...and it would NOT settle without the subtraction", (() => {
    const raw = (N) => { let s = 0; for (let n = -N; n <= N; n++) s += blktTerm(0.37, n, 1, 0.4, 0.3, 0); return s; };
    return Math.abs(raw(3200) - raw(200)) > 1;     /* logarithmic: about 2 ln 16 = 5.5 */
  })());
}

/* ------------------------------------------------------------------ THE control */

H("c -> 0: the roots must become the ordinary twisted tower");
{
  /* The free tower is computed in CLOSED FORM from the poles of the summand -- it is not this
   * module's root finder agreeing with itself.  Two independent objects meeting is the check. */
  for (const o of [{ m: 1, q: 0, alpha1: 0.4, alpha2: 0.3 },
                   { m: 2, q: 1, alpha1: 0.25, alpha2: 0.6 },
                   { m: 1, q: 1, alpha1: 0.0, alpha2: 0.0 },
                   { m: 3, q: 0, alpha1: 0.7, alpha2: 0.15 }]) {
    const free = blktFreeTower(o.m, o.q, o.alpha1, o.alpha2).filter((v) => v > 1e-9);
    const got = blktRoots({ ...o, c: 1e-9, N: 300 }, { count: 4, xMax: 2.2 });
    const worst = got.roots.slice(0, 4)
      .map((r, i) => Math.abs(r - free[i])).reduce((p, v) => Math.max(p, v), 0);
    ok(`m=${o.m} q=${o.q}: the four lowest roots ARE the free tower, to 1e-7`,
       got.roots.length >= 4 && worst < 1e-7,
       `got ${got.roots.slice(0, 4).map((v) => v.toFixed(7))} want ${free.slice(0, 4).map((v) => v.toFixed(7))}`);
  }

  /* and the reason a plain grid could not do this, stated as a fact rather than a memory */
  const o = { m: 1, q: 0, alpha1: 0.4, alpha2: 0.3, N: 200 };
  const pole = blktFreeTower(o.m, o.q, o.alpha1, o.alpha2).filter((v) => v > 1e-9)[0];
  const r = blktRoots({ ...o, c: 1e-9 }, { count: 1, xMax: 1 }).roots[0];
  ok("at tiny c the root sits inside 1e-6 of its pole, which is why the bracketing is by poles",
     Math.abs(r - pole) < 1e-6, `|root - pole| = ${Math.abs(r - pole).toExponential(2)}`);
}

H("turning c up moves the tower down, and by their own law");
{
  const o = { m: 1, q: 0, alpha1: 0.4, alpha2: 0.3, N: 300 };
  const lo = blktRoots({ ...o, c: 1e-9 }, { count: 1, xMax: 2 }).roots[0];
  const mid = blktRoots({ ...o, c: 1 }, { count: 1, xMax: 2 }).roots[0];
  const hi = blktRoots({ ...o, c: 15 }, { count: 1, xMax: 2 }).roots[0];
  ok("the lightest mode falls monotonically as c rises", lo > mid && mid > hi,
     `c=0 ${lo?.toFixed(5)}, c=1 ${mid?.toFixed(5)}, c=15 ${hi?.toFixed(5)}`);
}

H("THE JOIN: their (3.22), solved, is their (5.19), which is six pages later");
{
  /* Expanding (3.22) for alpha ~ x << 1 gives x = m|alpha| / (2 sqrt(1+c)), and at m = 1 that is
   * M_W^2 = (alpha_1^2 + alpha_2^2) / (4(1+c)R^2) -- their (5.19), p. 20.  Solving (3.22)
   * NUMERICALLY and hitting that closed form is the strongest check available on this module:
   * it uses two equations of theirs that we did not put in the same place. */
  const errs = [];
  for (const c of [0.5, 2, 15, 50])
    for (const A of [0.02, 0.005, 0.001]) {
      const o = { m: 1, q: 0, alpha1: 0.8 * A, alpha2: 0.6 * A, c };
      const got = blktApproxRoot(o), want = blktScaleFormula(o);
      errs.push({ c, A, rel: Math.abs(got - want) / want });
    }
  ok("(3.22) reproduces (5.19) to better than 1e-3 across c = 0.5 ... 50",
     errs.every((e) => e.rel < 1e-3),
     errs.filter((e) => e.rel >= 1e-3).map((e) => `c=${e.c} A=${e.A} ${e.rel.toExponential(1)}`).join(" "));

  /* AND IT CONVERGES LIKE AN EXPANSION SHOULD.  A fit that merely agreed would agree equally well
   * at every alpha; a genuine leading order improves quadratically as alpha shrinks. */
  const at = (A) => errs.find((e) => e.c === 15 && e.A === A).rel;
  const r1 = at(0.02) / at(0.005), r2 = at(0.005) / at(0.001);
  ok("...and the error falls like alpha^2, so it is the leading order and not a coincidence",
     r1 > 8 && r1 < 32 && r2 > 12 && r2 < 50,
     `ratios ${r1.toFixed(1)} (expect ~16) and ${r2.toFixed(1)} (expect ~25)`);

  /* m enters (5.19) linearly; check the implementation carries it */
  const om = { m: 3, q: 0, alpha1: 0.004, alpha2: 0.003, c: 15 };
  ok("m scales the answer, as (5.19) says it does",
     Math.abs(blktApproxRoot(om) - blktScaleFormula(om)) / blktScaleFormula(om) < 1e-3,
     `${blktApproxRoot(om)} vs ${blktScaleFormula(om)}`);
}

H("the potential (4.2), and what it does with a tower");
{
  const roots = [0.5, 1.2, 2.0];
  const V = blktVsector(roots, { LR: 20 });
  ok("a real scalar degree of freedom contributes NEGATIVELY, as (4.2) is written", V < 0);
  ok("a heavier tower contributes less, because e^{-x^2/l} cuts it off",
     Math.abs(blktVsector([3.0], { LR: 20 })) < Math.abs(blktVsector([0.5], { LR: 20 })));
  ok("raising the cutoff raises the magnitude, which is the cutoff dependence being real",
     Math.abs(blktVsector(roots, { LR: 40 })) > Math.abs(blktVsector(roots, { LR: 20 })));
  ok("an empty tower gives exactly zero, not NaN", blktVsector([], { LR: 20 }) === 0);
  ok("a root at zero is dropped rather than dividing by it",
     Number.isFinite(blktVsector([0, 1], { LR: 20 })));

  const s = blktSector({ m: 1, q: 0, alpha1: 0.4, alpha2: 0.3, c: 2, N: 200 },
                       { count: 3, xMax: 4, step: 0.002 });
  ok("a sector returns its roots WITH its potential, so neither can be quoted alone",
     Array.isArray(s.roots) && typeof s.V === "number" && s.LR === 20);
  ok("...and says how many pole intervals it had and whether it found what it was asked for",
     typeof s.poles === "number" && typeof s.complete === "boolean");
}

H("what this module does NOT claim");
{
  /* said out loud, because the identifiability control already proved it */
  ok("it takes ONE localized coefficient, not a sum over branes",
     blktMassEq.length === 2);
  console.log("  note the sum c = sum_i c_i does not determine the tower — two distributions with");
  console.log("  the same total give different spectral determinants (BLKT_IDENTIFIABILITY_CHECK.md),");
  console.log("  so `c` here is the single-brane case their section 3 writes, and nothing wider.");
  console.log("  note the full model potential (4.3) needs the field content and its (m,q)");
  console.log("  assignments, which live in their section 4 and are NOT implemented here.");
}

console.log(`\n${fail === 0 ? "PASSED" : "*** FAILED ***"}   ${pass} ok, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
