import {readFileSync} from 'node:fs';
import {hdDefaults,hdModel,hdCurve} from './src/modules/higgs_diagnostics.mjs';
import {robustness,higgsFromSum,invRFromSum} from './src/modules/robustness.mjs';
import {termTable} from './src/kernel/potential.mjs';
let passed=0,failed=0;
const check=(name,ok)=>{if(ok)passed++;else{failed++;console.error('FAIL '+name);}};
const near=(a,b,tol=3e-13)=>Number.isFinite(a)&&Math.abs(a-Number(b))<tol;
const throws=f=>{try{f();return false;}catch{return true;}};
const refs=JSON.parse(readFileSync('data/higgs_diagnostics_reference.json','utf8'));
for(const p of refs.rows){const r=hdModel(p);
  for(const k of ['rgg','finiteRgg','letRgg'])check(`70-digit ${k} at ${p.mKK}`,near(r[k],p[k]));
  check('partial leading tower overestimates infinite rate',r.finiteRgg>r.rgg);
  check('integral remainder encloses actual truncation',r.rateTail>=0&&r.rateTail<=r.rateTailBound);
  check('determinant sum suppresses further',r.letRgg<r.rgg);
}
const base=hdModel();
check('historical 1.32 TeV benchmark',near(base.rawBound,refs.boundGeV,1e-9)&&Math.abs(base.rawBound/1000-1.32)<.005);
check('historical provenance travels',base.provenance.includes('Historical'));
check('decoupling',hdModel({mKK:10000}).rgg>base.rgg&&hdModel({mKK:10000}).rgg<1);
check('numerical modes do not change physical rate',hdModel({modes:1}).rgg===hdModel({modes:1000}).rgg);
check('more modes improve truncation',hdModel({modes:1000}).rateTail<hdModel({modes:10}).rateTail);
check('scale changes comparison',hdModel({mKK:1000}).comparison==='below-window'&&base.comparison==='inside-window');
check('both edges constrain a custom window',hdModel({custom:true,lower:.89,upper:.95}).interval.upper>base.rawBound);
check('upper intersection is correct',near(hdModel({mKK:hdModel({custom:true,upper:.95}).interval.upper}).rgg,.95));
check('domain lower boundary is not experimental',hdModel({custom:true,lower:.5}).interval.lower===5*base.input.mTop);
check('no finite point for R>=1',hdModel({custom:true,lower:1,upper:1.19}).interval.empty);
check('window entirely below domain',hdModel({custom:true,lower:.5,upper:.6}).interval.empty);
const invalid=hdModel({mKK:500});
check('out-of-domain rate not quoted',invalid.rgg===null&&invalid.finiteRgg===null&&invalid.comparison==='not-evaluated');
for(const x of [{mKK:NaN},{mTop:0},{modes:1.5},{modes:0},{custom:true,lower:1,upper:.9},{custom:1}])check('reject invalid input '+JSON.stringify(x),throws(()=>hdModel(x)));
check('curve respects selected heavy-mass domain',hdCurve(hdDefaults()).every(p=>p.mKK>=5*173.34&&p.rgg<1));
const d=JSON.parse(readFileSync('data/su7_km25.json','utf8'));
const terms=termTable({bulk:[{rep:'28',parities:[1,1],multiplicity:1},{rep:'84',parities:[1,1],multiplicity:4}],conventions:{gauge_seed:'published'}},d);
const a=robustness(terms),b=robustness(terms,{g4:.7,g4Fraction:.2}),z=robustness(terms,{g4Fraction:0});
check('valid interior scans',a.m_h.valid&&a.invR5.valid&&a.m_h.convergenceOK&&a.invR5.convergenceOK);
check('shared geometry reproduces old independent Higgs evaluation',near(a.m_h.base,higgsFromSum(terms,a.base),1e-10));
check('shared geometry reproduces old independent scale evaluation',near(a.invR5.base,invRFromSum(terms,a.base),1e-10));
check('g4 changes mass proportionally',near(b.m_h.base/a.m_h.base,.7/.63));
check('g4 cannot move scale',a.invR5.base===b.invR5.base&&b.invR5.model===0);
check('configurable model span reaches actual extrema',near(b.m_h.raw.scans[1].lo,.8*b.m_h.base,1e-10)&&near(b.m_h.raw.scans[1].hi,1.2*b.m_h.base,1e-10));
check('zero model span does not invent model uncertainty',z.m_h.model===0&&z.m_h.measured>0);
check('measured fractional uncertainty consistent in both quantities',near(a.m_h.measured/a.m_h.base,a.invR5.measured/a.invR5.base));
check('four actual vacuum evaluations',a.vacua.length===4);
const none=robustness([]);
check('no minimum refuses robustness',!none.m_h.valid&&!none.invR5.valid&&none.m_h.verdict.word==='not-determined');
check('failed minima remain visible in raw data',none.m_h.raw.scans.every(s=>s.failed===s.values.length));
for(const x of [{g4Fraction:1},{g4:NaN},{windings:1},{mWErr:-1}])check('reject invalid scan settings',throws(()=>robustness(terms,x)));
console.log(`${failed?'FAILED':'PASSED'}   ${passed} ok, ${failed} failed`);
process.exitCode=failed?1:0;
