/* card_demo.js — 🎬 guided simulations of every menu section, Simulator mode and experiment card: a Demo button
 * presses the real controls in order, a banner at the top says what each step shows, and a closing panel says how to
 * read what appeared.  The pattern of tafagent's demos (karlesmarin.github.io/tafagent).
 *
 * Copyright (c) 2026 Carles Marin. All rights reserved.
 * Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
 *
 * ONE SOURCE.  The steps come from the video guide's storyboard (CDM_SCRIPTS, generated by
 * tools/make_demo_scripts.mjs), so the demo and the video run the same actions and say the same thing; the closing
 * panel is the "how to read it" of the user guide.  A card may carry a hand-written script instead (CDM_DEMOS) when
 * its banner should quote live numbers — the first KK gluon does.
 * NOTHING IS FAKED.  A step writes the real input or presses the real button and fires the events a reader's edit
 * fires; the page recomputes for real; a value that does not persist stops the demo with the reason on screen.
 * IT CAN BE STOPPED OR HURRIED.  ✕ aborts at the next pause; "Next ▶" skips the reading time of a step.
 * A LINK CAN START IT.  `#s=<section>&demo=<id>` (or `?demo=<id>`) runs a demo once its panel is mounted; `lang=es`
 * picks Spanish; `demoSpeed` (tests only) scales every pause.  build/demos.mjs runs all of them in a browser.
 */
const CDM_URL = (() => {
  try { const q = new URLSearchParams(location.search), h = new URLSearchParams(location.hash.replace(/^#/, ''));
    return { demo: h.get('demo') || q.get('demo'), lang: h.get('lang') || q.get('lang'), speed: Number(h.get('demoSpeed') || q.get('demoSpeed')) || 1 };
  } catch { return { demo: null, lang: null, speed: 1 }; }
})();
const CDM_STATE = { running: null, cancel: false, skip: false, autostarted: false, lastError: null, lastFinished: null };
const cdmLang = () => (CDM_URL.lang === 'es' || CDM_URL.lang === 'en') ? CDM_URL.lang
  : (typeof GUIDE_LANGUAGE !== 'undefined' && GUIDE_LANGUAGE === 'es' ? 'es' : 'en');
const cdmNum = (x, d = 2) => (x == null || !Number.isFinite(x)) ? '—' : Number(x).toFixed(d);
const cdmChapters = () => (typeof CDM_SCRIPTS !== 'undefined' ? CDM_SCRIPTS.chapters : []);
const cdmChapter = id => cdmChapters().find(c => c.id === id) || null;
/* live readers for section demos: what the section itself prints, quoted — so a demo never states what the page does not */
const cdmT = sel => (document.querySelector(sel)?.textContent || '').replace(/\s+/g, ' ').trim();
const cdmV = sel => document.querySelector(sel)?.value ?? '';
/* Block-aware text: a block element (a box, a row, a paragraph) ends its own phrase, so "1,286 tiles drawn" and
 * "Sorted by…" do not run together.  textContent, not innerText: innerText applies CSS text-transform (UPPERCASE labels). */
const CDM_BLOCK = new Set(['DIV', 'P', 'LI', 'TR', 'TABLE', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'SECTION', 'DETAILS', 'SUMMARY', 'UL', 'OL', 'TBODY', 'THEAD']);
function cdmBT(sel) {
  const el = document.querySelector(sel); if (!el) return '';
  let out = '';
  /* a block is decided by layout, not by tag: a <b> styled display:block ends its phrase too; table cells are spaced */
  const BLOCKISH = new Set(['block', 'flex', 'grid', 'list-item', 'table', 'table-row', 'flow-root', 'table-row-group', 'table-header-group', 'table-caption']);
  const kind = c => { const d = getComputedStyle(c).display;
    return d === 'table-cell' ? 'cell' : (CDM_BLOCK.has(c.tagName) || BLOCKISH.has(d)) ? 'block' : 'inline'; };
  const walk = n => { for (const c of n.childNodes) {
    if (c.nodeType === 3) out += c.data.replace(/\s+/g, ' ');                                   // source line breaks are spaces
    else if (c.nodeType === 1) {
      if (c.tagName === 'BR') { out += ' '; continue; }                                        // a line break inside a sentence
      if (c.childElementCount === 0 && c.textContent.trim() === 'i') continue;                 // the ⓘ info glyph
      const k = kind(c); if (k === 'block') out += '\n'; walk(c); out += k === 'block' ? '\n' : k === 'cell' ? ' ' : '';
    }
  } };
  walk(el);
  return out.split(/\n+/).map(s => s.replace(/\s+/g, ' ').trim()).filter(Boolean)
    .map(s => /[.!?:;,—–]$/.test(s) ? s : s + '.').join(' ');
}
/* a sentence ends at . ! ? followed by a space and a capital — never inside "1.92 TeV" */
const CDM_ABBR = /\b(eq|eqs|Eq|Eqs|Fig|Figs|Ref|Refs|Sec|Secs|Thm|Phys|Rev|Lett|Math|Nucl|Mod|J|Proc|Vol|No|vs|al|cf|e\.g|i\.e|Prop|Lemma|Cor|Part|App|Ch)\.$/;
const cdmSentences = sel => {
  const raw = cdmBT(sel).split(/(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÑ«“"])/), out = [];
  for (const piece of raw) { if (out.length && CDM_ABBR.test(out[out.length - 1])) out[out.length - 1] += ' ' + piece; else out.push(piece); }
  return out;
};
/* many panels open with a short headline ("And it was just checked."): a quote then carries the sentence that has the data */
const cdmS = (sel, n = 1) => { const p = cdmSentences(sel); const k = (p[0] || '').length < 60 && p.length > n ? n + 1 : n; return p.slice(0, k).join(' ').trim(); };
const cdmLast = sel => cdmSentences(sel).at(-1) || '';
const cdmFind = (sel, re) => cdmSentences(sel).find(s => re.test(s)) || '';
const cdmEsc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/* Hand-written card scripts, for banners that quote the card's numbers as they appear.  `v` is the current result. */
const CDM_DEMOS = {
  kkgluon: {
    model: () => kkgModel(RX_STATE.kkgluon),
    steps: [
      { en: () => 'First KK gluon at the LHC: this card compares a Kaluza–Klein gluon with ATLAS and CMS data',
        es: () => 'Primer gluón KK en el LHC: esta tarjeta compara un gluón de Kaluza–Klein con datos de ATLAS y CMS',
        hl: '#rx_kkgluon h2' },
      { en: () => 'Load the published warped benchmark (Casagrande et al. 2008)',
        es: () => 'Carga el punto de referencia curvado publicado (Casagrande et al. 2008)',
        button: 'Published RS point (arXiv:0807.4937)' },
      { en: v => `At 3.75 TeV: Γ/M = ${cdmNum(v.here.GoverM)}, BR(tt̄) = ${cdmNum(v.here.BRtt)}, and r = σ×BR / ATLAS limit = ${cdmNum(v.values.r_tt_observed.value)} — at the edge (a comparison with ATLAS's 30%-width benchmark, not an exclusion)`,
        es: v => `A 3,75 TeV: Γ/M = ${cdmNum(v.here.GoverM)}, BR(tt̄) = ${cdmNum(v.here.BRtt)} y r = σ×BR / límite de ATLAS = ${cdmNum(v.values.r_tt_observed.value)}: en el borde (comparación con la plantilla del 30 % de ATLAS, no una exclusión)`,
        hl: '#rx_kkgluon_result > p' },
      { en: () => 'The tt̄ rate against the ATLAS observed limit, as the mass is scanned',
        es: () => 'La tasa tt̄ frente al límite observado de ATLAS, barriendo la masa',
        hl: '#rx_kkgluon_result svg', index: 0 },
      { en: v => `The m(tt̄) spectrum in the 15 CMS bins: the interference with the QCD gluon is ${v.values.interference_below_pole.value} below the pole (light-quark and top couplings of opposite sign)`,
        es: v => `El espectro m(tt̄) en los 15 intervalos de CMS: la interferencia con el gluón de QCD es ${v.values.interference_below_pole.value === 'constructive' ? 'constructiva' : 'destructiva'} bajo el polo (acoplos del quark ligero y del top de signo opuesto)`,
        hl: '#rx_kkgluon_result svg', index: 2 },
      { en: () => 'Now the flat GHU coloron at 4.5 TeV: every quark couples √2 g_s',
        es: () => 'Ahora el coloron de GHU plana a 4,5 TeV: todos los quarks acoplan √2 g_s',
        button: 'Flat GHU coloron · 4.5 TeV' },
      { en: v => `Same-sign couplings: the interference turns ${v.values.interference_below_pole.value} and the low bins go down (largest change ${cdmNum(100 * v.values.tt_spectrum_largest_shift.value, 1)}%)`,
        es: v => `Acoplos del mismo signo: la interferencia se vuelve ${v.values.interference_below_pole.value === 'destructive' ? 'destructiva' : 'constructiva'} y los intervalos bajos bajan (mayor cambio ${cdmNum(100 * v.values.tt_spectrum_largest_shift.value, 1)} %)`,
        hl: '#rx_kkgluon_result svg', index: 2 },
      { en: v => `Expected Δχ² against the CMS covariance with 10% SM-theory error: ${cdmNum(v.values.tt_spectrum_dchi2.value)}; it falls to 3.84 at ${cdmNum(v.values.tt_spectrum_reach_GeV.value / 1000)} TeV`,
        es: v => `Δχ² esperado frente a la covarianza de CMS con un 10 % de error teórico del SM: ${cdmNum(v.values.tt_spectrum_dchi2.value)}; baja a 3,84 a ${cdmNum(v.values.tt_spectrum_reach_GeV.value / 1000)} TeV`,
        hl: '#rx_kkgluon_result svg', index: 3 },
      { en: () => 'Set the SM theory uncertainty to zero…',
        es: () => 'Pon a cero la incertidumbre teórica del SM…',
        set: ['#rx_kkgluon_controls [data-rx="ttTheory"]', 0] },
      { en: v => `…and the reach moves to ${cdmNum(v.values.tt_spectrum_reach_GeV.value / 1000)} TeV: the comparison is only as good as the SM prediction it assumes`,
        es: v => `…y el alcance pasa a ${cdmNum(v.values.tt_spectrum_reach_GeV.value / 1000)} TeV: la comparación vale lo que vale la predicción del SM que supone`,
        hl: '#rx_kkgluon_result svg', index: 3 },
    ],
    explain: {
      en: { title: '📊 How to read this card',
        lines: ['<b>r = prediction / published limit</b>, in each experiment\'s own convention. r ≥ 1 means the leading-order rate exceeds that benchmark\'s limit — a comparison, not a validated exclusion at another width.',
          '<b>The m(tt̄) spectrum</b> includes the interference with QCD, whose sign below the pole is −sign(v<sub>q</sub>v<sub>t</sub>), v = (c<sub>L</sub>+c<sub>R</sub>)/2.',
          '<b>Δχ²</b> is the separation of SM and SM + KK gluon in units of the CMS covariance if the data equal the SM: a sensitivity, not a limit. It moves with the SM theory error you assume.',
          '<b>Certificates</b> (open the box below the tables): couplings against a 40-digit reference; ATLAS\'s and CMS\'s own theory curves reproduced; the spectrum against an independent Dirac-trace and LHAPDF computation, recomputed in this page.',
          '👉 <b>Now try your own point:</b> change the mass, kL or any c value above; every number recomputes.'] },
      es: { title: '📊 Cómo leer esta tarjeta',
        lines: ['<b>r = predicción / límite publicado</b>, en la convención de cada experimento. r ≥ 1 significa que la tasa a primer orden supera el límite de ese benchmark: una comparación, no una exclusión validada a otra anchura.',
          '<b>El espectro m(tt̄)</b> incluye la interferencia con QCD, cuyo signo bajo el polo es −signo(v<sub>q</sub>v<sub>t</sub>), v = (c<sub>L</sub>+c<sub>R</sub>)/2.',
          '<b>Δχ²</b> es la separación entre SM y SM + gluón KK en unidades de la covarianza de CMS si los datos son el SM: una sensibilidad, no un límite. Se mueve con el error teórico del SM que supongas.',
          '<b>Certificados</b> (abre la caja bajo las tablas): acoplos frente a una referencia de 40 dígitos; las curvas teóricas de ATLAS y CMS reproducidas; el espectro frente a un cálculo independiente con trazas de Dirac y LHAPDF, recalculado en esta página.',
          '👉 <b>Prueba ahora tu propio punto:</b> cambia la masa, kL o cualquier c arriba; todo se recalcula.'] },
    },
  },
};

/* ---------- the stage: pauses, banner, highlight ---------- */
function cdmSleep(ms) {
  return new Promise((resolve, reject) => setTimeout(() => CDM_STATE.cancel ? reject(new Error('demo stopped')) : resolve(), ms * CDM_URL.speed));
}
/* the reading time of a step, which "Next ▶" cuts short */
async function cdmRead(ms) {
  const end = Date.now() + ms * CDM_URL.speed; CDM_STATE.skip = false;
  while (Date.now() < end) {
    if (CDM_STATE.cancel) throw new Error('demo stopped');
    if (CDM_STATE.skip) { CDM_STATE.skip = false; return; }
    await new Promise(r => setTimeout(r, Math.min(120, Math.max(1, end - Date.now()))));
  }
}
function cdmCss() {
  if (document.getElementById('cdm_css')) return;
  const s = document.createElement('style'); s.id = 'cdm_css';
  s.textContent = '.cdm-hl{outline:3px solid #34b3e0!important;outline-offset:3px;border-radius:6px;box-shadow:0 0 0 6px rgba(52,179,224,.25)!important;transition:all .3s}' +
    '#cdm_banner{position:fixed;top:0;left:0;right:0;z-index:100000;padding:12px 150px 12px 20px;font:600 15.5px/1.45 system-ui,sans-serif;color:#fff;text-align:center;background:linear-gradient(135deg,#0b5e7a,#2a9fc4);box-shadow:0 2px 14px rgba(0,0,0,.35);max-height:40vh;overflow:auto}' +
    '#cdm_banner .cdm-ctl{position:absolute;right:12px;top:8px;display:flex;gap:6px}#cdm_banner .cdm-ctl button{background:transparent;border:1px solid #fff8;color:#fff;border-radius:6px;padding:2px 9px;cursor:pointer;width:auto;font:600 13px system-ui}' +
    '#cdm_explain{margin:16px 0;padding:14px 18px;border-radius:10px;border:1px solid var(--line,#cfd8de);background:var(--card,#fff);box-shadow:0 4px 16px rgba(0,0,0,.08);line-height:1.55}' +
    '#cdm_explain h3{margin:0 0 8px;color:#0b5e7a}#cdm_explain p{margin:6px 0}' +
    '.cdm-menu{position:absolute;z-index:200;background:var(--card,#fff);border:1px solid var(--line,#cfd8de);border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,.15);padding:6px;display:flex;flex-direction:column;gap:2px;font-weight:400;min-width:260px}' +
    '.cdm-menu button{text-align:left;width:100%;padding:6px 10px}';
  document.head.appendChild(s);
}
function cdmBanner(html, step, total) {
  let el = document.getElementById('cdm_banner');
  if (!el) { el = document.createElement('div'); el.id = 'cdm_banner'; el.setAttribute('role', 'status'); document.body.appendChild(el); }
  const es = cdmLang() === 'es';
  el.innerHTML = (step ? `<span style="opacity:.8">${es ? 'Paso' : 'Step'} ${step}/${total} · </span>` : '') + html +
    `<span class="cdm-ctl">${step ? `<button type="button" data-cdm-next>${es ? 'Siguiente ▶' : 'Next ▶'}</button>` : ''}<button type="button" data-cdm-stop aria-label="${es ? 'Parar la demo' : 'Stop the demo'}">✕</button></span>`;
  el.querySelector('[data-cdm-stop]').onclick = () => { CDM_STATE.cancel = true; cdmHide(); };
  const next = el.querySelector('[data-cdm-next]'); if (next) next.onclick = () => { CDM_STATE.skip = true; };
}
function cdmHide() { document.getElementById('cdm_banner')?.remove(); document.querySelectorAll('.cdm-hl').forEach(e => e.classList.remove('cdm-hl')); }
/* a tall target (a whole section) is read from its top; a small one is brought to the middle */
function cdmScroll(el) {
  if (!el) return;
  const tall = el.getBoundingClientRect().height > 0.8 * innerHeight;
  el.scrollIntoView({ block: tall ? 'start' : 'center', behavior: CDM_URL.speed < 1 ? 'auto' : 'smooth' });
}
function cdmHighlight(selector, index = 0) {
  document.querySelectorAll('.cdm-hl').forEach(e => e.classList.remove('cdm-hl'));
  const el = typeof selector === 'string' ? document.querySelectorAll(selector)[index] : selector;
  if (el) { for (let p = el; p; p = p.parentElement) if (p.tagName === 'DETAILS') p.open = true; el.classList.add('cdm-hl'); cdmScroll(el); }
  return el;
}

/* ---------- the actions the video recorder performs, done in the page ---------- */
function cdmTarget(a) {
  const el = a.kind === 'button' ? [...document.querySelectorAll('#section button')].find(e => e.textContent.trim() === a.text)
    : document.querySelectorAll(a.selector)[a.index || 0];
  if (!el) throw new Error('missing control: ' + (a.selector || a.text));
  for (let p = el; p; p = p.parentElement) if (p.tagName === 'DETAILS') p.open = true;
  return el;
}
function cdmPointer(el, x = 0.5, y = 0.5) {
  const r = el.getBoundingClientRect(), o = { bubbles: true, cancelable: true, clientX: r.left + r.width * x, clientY: r.top + r.height * y, button: 0 };
  for (const t of ['pointerdown', 'mousedown', 'pointerup', 'mouseup', 'click'])
    el.dispatchEvent(t.startsWith('pointer') && typeof PointerEvent === 'function' ? new PointerEvent(t, o) : new MouseEvent(t, o));
}
async function cdmAct(a) {
  if (a.kind === 'demoStart') a = { kind: 'click', selector: '#demoRun', pauseDemo: true };
  let el = cdmTarget(a); cdmHighlight(el);
  if (a.kind === 'scroll') { await cdmSleep(500); return; }
  await cdmSleep(900);
  el = cdmTarget(a);
  if (a.kind === 'set') {
    if (el.tagName === 'SELECT' && ![...el.options].some(o => o.value === String(a.value))) throw new Error(`invalid option ${a.value} for ${a.selector}`);
    if (el.type === 'checkbox') el.checked = !!a.value; else el.value = String(a.value);
    el.dispatchEvent(new Event(el.tagName === 'SELECT' || el.type === 'checkbox' ? 'change' : 'input', { bubbles: true }));
    const n = cdmTarget(a); if (n.tagName !== 'SELECT' && n.type !== 'checkbox') n.dispatchEvent(new Event('change', { bubbles: true }));
  } else if (a.kind === 'canvasClick') cdmPointer(el, a.x ?? 0.5, a.y ?? 0.5);
  else el.click();
  if (a.pauseDemo && typeof DEMO_S !== 'undefined') { clearTimeout(DEMO_S.timer); DEMO_S.timer = null; document.getElementById('demoBar')?.remove(); }
  for (let i = 0; i < 600; i++) { let busy = false; try { busy = !!cdmTarget(a).disabled; } catch { break; } if (!busy) break; if (i === 599) throw new Error('control stayed busy: ' + (a.selector || a.text)); await cdmSleep(100); }
  await cdmSleep(400);
  if (a.kind === 'set') {
    let after = null; try { after = cdmTarget(a); } catch { return; }   // a set that navigates away is allowed
    const actual = after.type === 'checkbox' ? after.checked : after.value;
    if (String(actual) !== String(a.value) && Number(actual) !== Number(a.value)) throw new Error(`value did not persist: ${a.selector} wanted ${a.value}, got ${actual}`);
  }
}

/* ---------- running a demo ---------- */
function cdmClosePanel(id, title, lines) {
  document.getElementById('cdm_explain')?.remove();
  const p = document.createElement('div'); p.id = 'cdm_explain';
  p.innerHTML = `<h3>${title}</h3>` + lines.map(l => `<p>${l}</p>`).join('');
  const ch = cdmChapter(id), card = ch?.card || (CDM_DEMOS[id] ? `rx_${id}` : null);
  const anchor = card && document.getElementById(`${card}_result`);
  if (anchor) anchor.after(p);
  else { const how = document.querySelector('#section > details.howto'); if (how) how.after(p); else document.getElementById('section')?.prepend(p); }
  cdmScroll(p);
}
/* A hand-written step is one of: { button } presses a preset (in the card, else anywhere in the section);
 * { set: [selector, value or v => value] } edits a control; { hl, index } or { fig } points at something and gives the
 * reader time to read.  `pre` (actions in the recorder's vocabulary) prepares the section silently first — e.g. the
 * Simulator mode a card lives in.  Every banner is written from the card's result at that moment. */
async function cdmRunHand(id) {
  const d = CDM_DEMOS[id], lang = cdmLang(), total = d.steps.length;
  for (const a of d.pre || []) await cdmAct(a);
  for (let i = 0; i < total; i++) {
    const s = d.steps[i];
    if (s.button) {
      const b = [...document.querySelectorAll(`#rx_${id} button`)].find(x => x.textContent.trim() === s.button)
        || [...document.querySelectorAll('#section button')].find(x => x.textContent.trim() === s.button);
      if (!b) throw new Error('missing button: ' + s.button);
      cdmBanner(s[lang](d.model()), i + 1, total); cdmHighlight(b); await cdmSleep(1400); b.click(); await cdmSleep(900);
      if (s.then) { cdmBanner(s.then[lang](d.model()), i + 1, total); cdmHighlight(s.then.hl || `#rx_${id}_result > p`, s.then.index || 0); await cdmRead(4200); }
    } else if (s.act) {
      cdmBanner(s[lang](d.model()), i + 1, total); await cdmAct(s.act);
      if (s.then) { cdmBanner(s.then[lang](d.model()), i + 1, total); if (!cdmHighlight(s.then.hl, s.then.index || 0)) throw new Error('missing target: ' + s.then.hl); await cdmRead(4200); }
    } else if (s.click) {
      const el = document.querySelector(s.click);
      if (!el) throw new Error('missing control: ' + s.click);
      cdmBanner(s[lang](d.model()), i + 1, total); cdmHighlight(el); await cdmSleep(1400); el.click(); await cdmSleep(900);
      for (let k = 0; k < 600 && document.querySelector(s.click)?.disabled; k++) await cdmSleep(100);
      if (s.then) { cdmBanner(s.then[lang](d.model()), i + 1, total); if (!cdmHighlight(s.then.hl || s.click, s.then.index || 0)) throw new Error('missing target: ' + s.then.hl); await cdmRead(4200); }
    } else if (s.set) {
      const [sel, value] = s.set, input = document.querySelector(sel);
      if (!input) throw new Error('missing control: ' + sel);
      const v = typeof value === 'function' ? value(d.model()) : value;
      cdmBanner(s[lang](d.model()), i + 1, total); cdmHighlight(sel); await cdmSleep(1400);
      if (input.type === 'checkbox') { input.checked = !!v; input.dispatchEvent(new Event('change', { bubbles: true })); }
      else { input.value = String(v); input.dispatchEvent(new Event(input.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true }));
        input.dispatchEvent(new Event('change', { bubbles: true })); }
      await cdmSleep(900);
      const now = document.querySelector(sel);
      if (now && (now.type === 'checkbox' ? now.checked !== !!v : (String(now.value) !== String(v) && Number(now.value) !== Number(v)))) throw new Error(`value did not persist: ${sel} wanted ${v}, got ${now.type === 'checkbox' ? now.checked : now.value}`);
      if (s.then) { cdmBanner(s.then[lang](d.model()), i + 1, total); cdmHighlight(s.then.hl || `#rx_${id}_result > p`, s.then.index || 0); await cdmRead(4200); }
    } else {
      await cdmSleep(150);
      const hl = s.fig != null ? `#rx_${id}_result svg` : s.hl, index = s.fig != null ? s.fig : (s.index || 0);
      cdmBanner(s[lang](d.model()), i + 1, total);
      if (!cdmHighlight(hl, index)) throw new Error('missing target: ' + hl + ' #' + index);
      await cdmRead(s.read || 4200);
    }
  }
  if (d.explain === 'guide') { const g = cdmGuideClose(id); cdmClosePanel(id, g.title, g.lines); }
  else { const x = d.explain[lang]; cdmClosePanel(id, x.title, x.lines); }
}
/* the closing panel from the user guide's own "how to read it" — curated text, not a conclusion written for the demo */
function cdmGuideClose(id) {
  const c = cdmChapter(id), lang = cdmLang(), es = lang === 'es', close = c?.close?.[lang], lines = [];
  if (close?.read) lines.push(cdmEsc(close.read));
  if (close?.expect) lines.push(`<b>${es ? 'Qué esperar:' : 'What to expect:'}</b> ${cdmEsc(close.expect)}`);
  if (close?.guide && typeof guideHref === 'function') lines.push(`<a href="${guideHref(close.guide)}" target="_blank" rel="noopener">${es ? 'Guía completa ↗' : 'Full guide ↗'}</a>`);
  lines.push(es ? '👉 <b>Ahora prueba tú:</b> cambia un parámetro cada vez y lee el resultado con su alcance.' : '👉 <b>Now try it yourself:</b> change one input at a time and read the result with its scope.');
  return { title: (es ? '📊 Cómo leerlo · ' : '📊 How to read it · ') + cdmEsc(c ? (es ? c.titleES : c.title) : id), lines };
}
async function cdmRunChapter(id) {
  const c = cdmChapter(id), lang = cdmLang(), total = c.steps.length, es = lang === 'es';
  for (const a of c.setup) await cdmAct(a);
  for (let i = 0; i < total; i++) {
    const s = c.steps[i];
    cdmBanner(cdmEsc(s[lang]), i + 1, total);
    if (s.focus?.selector) { try { cdmHighlight(s.focus.selector, s.focus.index || 0); } catch {} }
    const t0 = Date.now();
    for (const a of s.actions) await cdmAct(a);
    if (s.focus?.selector) { const f = document.querySelectorAll(s.focus.selector)[s.focus.index || 0]; if (f) cdmHighlight(f); }
    const reading = Math.max(4000, s[lang].length * 55) - (Date.now() - t0) / CDM_URL.speed;
    await cdmRead(Math.max(1200, reading));
  }
  const close = c.close[lang], lines = [];
  if (close?.read) lines.push(cdmEsc(close.read));
  if (close?.expect) lines.push(`<b>${es ? 'Qué esperar:' : 'What to expect:'}</b> ${cdmEsc(close.expect)}`);
  if (close?.guide && typeof guideHref === 'function') lines.push(`<a href="${guideHref(close.guide)}" target="_blank" rel="noopener">${es ? 'Guía completa ↗' : 'Full guide ↗'}</a>`);
  lines.push(es ? '👉 <b>Ahora prueba tú:</b> cambia un parámetro cada vez y lee el resultado con su alcance.' : '👉 <b>Now try it yourself:</b> change one input at a time and read the result with its scope.');
  cdmClosePanel(id, (es ? '📊 Cómo leerlo · ' : '📊 How to read it · ') + cdmEsc(es ? c.titleES : c.title), lines);
}
async function cdmRun(id) {
  if (CDM_STATE.running || !(CDM_DEMOS[id] || cdmChapter(id))) return;
  CDM_STATE.running = id; CDM_STATE.cancel = false; CDM_STATE.lastError = null; cdmCss();
  document.getElementById('cdm_explain')?.remove();
  const es = cdmLang() === 'es';
  try {
    if (CDM_DEMOS[id]) await cdmRunHand(id); else await cdmRunChapter(id);
    CDM_STATE.lastFinished = id;
    cdmBanner(es ? '✓ Hecho. Lee la explicación y prueba tu propio punto.' : '✓ Done. Read the explanation and try your own point.', 0, 0);
    setTimeout(() => { if (!CDM_STATE.running) cdmHide(); }, 12000 * CDM_URL.speed);
  } catch (e) {
    if (CDM_STATE.cancel) cdmHide();
    else { CDM_STATE.lastError = `${id}: ${e && e.message}`; console.warn('demo failed:', CDM_STATE.lastError);
      cdmBanner((es ? 'La demo se detuvo: ' : 'The demo stopped: ') + cdmEsc(e && e.message), 0, 0); }
  } finally { CDM_STATE.running = null; }
}

/* ---------- where the buttons live ---------- */
const cdmSectionDemos = section => cdmChapters().filter(c => c.host === section && !c.card);
/* in the how-to summary of a section (howto.js); several demos in one section open a small menu */
function cdmSectionButton(section) {
  const list = cdmSectionDemos(section);
  if (!list.length) return '';
  const tip = cdmLang() === 'es' ? 'Mira una simulación guiada' : 'Watch a guided simulation';
  return `<button type="button" class="ghost cdm-sec" data-cdm-section="${cdmEsc(section)}" title="${tip}" style="float:right;width:auto;padding:2px 10px;margin-left:8px">🎬 Demo${list.length > 1 ? ' ▾' : ''}</button>`;
}
function cdmMenu(button, list) {
  document.querySelector('.cdm-menu')?.remove();
  const m = document.createElement('div'); m.className = 'cdm-menu'; const es = cdmLang() === 'es';
  m.innerHTML = list.map(c => `<button type="button" class="ghost" data-cdm-run="${cdmEsc(c.id)}">${cdmEsc(es ? c.titleES : c.title)}</button>`).join('');
  const r = button.getBoundingClientRect();
  m.style.left = Math.max(8, r.right + scrollX - 280) + 'px'; m.style.top = (r.bottom + scrollY + 4) + 'px';
  document.body.appendChild(m);
}
if (typeof document !== 'undefined' && typeof document.addEventListener === 'function') {
  document.addEventListener('click', e => {
    const t = e.target && e.target.closest ? e.target : null; if (!t) return;
    const sec = t.closest('[data-cdm-section]'), run = t.closest('[data-cdm-run]');
    if (sec) {
      e.preventDefault(); e.stopPropagation(); cdmCss();
      const list = cdmSectionDemos(sec.dataset.cdmSection);
      if (list.length === 1) cdmRun(list[0].id); else cdmMenu(sec, list);
    } else if (run) { e.preventDefault(); document.querySelector('.cdm-menu')?.remove(); cdmRun(run.dataset.cdmRun); }
    else if (!t.closest('.cdm-menu')) document.querySelector('.cdm-menu')?.remove();
  }, true);
}
/* in a card heading (rxMount) */
function cdmButton(id) {
  if (typeof document === 'undefined' || typeof document.querySelector !== 'function') return;   // Node smoke runs with a stub DOM
  if (!(CDM_DEMOS[id] || cdmChapters().some(c => c.card === `rx_${id}`))) return;
  const demoId = CDM_DEMOS[id] ? id : cdmChapters().find(c => c.card === `rx_${id}`).id;
  const h = document.querySelector(`#rx_${id} h2`);
  if (h && !h.querySelector('.cdm-btn')) {
    const b = document.createElement('button'); b.type = 'button'; b.className = 'ghost cdm-btn';
    b.textContent = '🎬 Demo'; b.title = cdmLang() === 'es' ? 'Mira una simulación guiada de esta tarjeta' : 'Watch a guided simulation of this card';
    b.style.cssText = 'margin-left:10px;width:auto;padding:2px 10px;font-size:13px;vertical-align:middle';
    b.onclick = () => cdmRun(demoId); h.appendChild(b);
  }
}
/* a link with demo=<id> starts that demo once its panel is on screen */
if (CDM_URL.demo && typeof document !== 'undefined' && typeof document.querySelector === 'function') {
  /* deferred: the build inlines views before modules, so CDM_SCRIPTS exists only once the whole page has loaded */
  const id = CDM_URL.demo; let tries = 0, ch, card;
  const ready = () => card ? !!document.querySelector(`#${card} h2`) : (ch && document.querySelector('#rail a.on')?.dataset.id === ch.host);
  const wait = () => {
    if (CDM_STATE.autostarted) return;
    /* a card demo waits for its card; a section demo (hand-written or not) waits for its section */
    if (ch === undefined) { ch = cdmChapter(id); card = ch ? ch.card : (CDM_DEMOS[id] ? `rx_${id}` : null); }
    if (ready()) { CDM_STATE.autostarted = true; setTimeout(() => { if (card) document.getElementById(card)?.scrollIntoView({ block: 'start' }); cdmRun(id); }, 900 * CDM_URL.speed); }
    else if (++tries < 300) setTimeout(wait, 100);
  };
  setTimeout(wait, 100);
}
