"""Embed the reviewed JSON records for offline use in the laboratory."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def main():
    records=[('THERMAL_CROSSVALIDATION','thermal_crossvalidation.json'),('UNCERTAINTY_BUDGET','uncertainty_budget.json')]
    text='/* Generated by tools/build_crossvalidation_reference.py; sources retain authorship. */\n'
    for symbol,name in records:
        obj=json.loads((ROOT/'data'/name).read_text())
        text+='export const '+symbol+' = '+json.dumps(obj,separators=(',',':'))+';\n'
    (ROOT/'src/modules/crossvalidation_reference.mjs').write_text(text,encoding='utf-8',newline='\n')
    print('Embedded thermal comparison and conditional uncertainty budget.')
if __name__=='__main__': main()
