/* Generate the in-page reference modules from the pinned data files (DESIGN D7: precompute and pin; the page must
 * run from file://, so data travels as JavaScript, not as fetched JSON).
 *   node tools/make_xs_references.mjs
 * -> src/modules/xs_lumi_reference.mjs     parton luminosities (7 significant digits) + PDF provenance + certificates
 *    src/modules/xs_limits_reference.mjs   ATLAS tt̄ (2512.17856, Fig. 10c) and CMS dijet (1911.03947) limit columns
 *    src/modules/rf_benchmark_reference.mjs the RS reference point of arXiv:0807.4937 Sec. 6.3
 *    src/modules/tt_cms_reference.mjs      CMS parton-level dσ/dm(tt̄), absolute and normalised, with covariances
 *    src/modules/tts_reference.mjs         the independent reference of tt_spectrum.mjs (tools/tt_spectrum_reference.py)
 * Each module records the sha256 of the data file it came from; _test_kk_gluon_lhc.mjs checks the modules against
 * the files number by number. */
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const raw=p=>readFileSync(resolve(root,p)),J=p=>JSON.parse(raw(p).toString('utf8')),sha=p=>createHash('sha256').update(raw(p)).digest('hex');
const sig=x=>x==null?null:Number(Number(x).toPrecision(7));
const head=(what,files)=>`/* Generated by tools/make_xs_references.mjs — do not edit by hand. ${what}\n * Sources: ${files.map(f=>`${f} sha256 ${sha(f)}`).join('; ')} */\n`;

const L=J('data/parton_lumi_13TeV.json');
const lumi={sqrts_GeV:L.sqrts_GeV,pdf:L.pdf,definition:L.definition,grid_sqrtshat_GeV:L.grid_sqrtshat_GeV,
  tables:Object.fromEntries(Object.entries(L.tables).map(([s,t])=>[s,Object.fromEntries(Object.entries(t).map(([c,col])=>[c,col.map(sig)]))])),
  certificates:L.certificates,source:{file:'data/parton_lumi_13TeV.json',sha256:sha('data/parton_lumi_13TeV.json'),tool:'tools/make_parton_lumi.py in tools/pdf.Dockerfile'}};
writeFileSync(resolve(root,'src/modules/xs_lumi_reference.mjs'),head('Parton luminosities at 13 TeV.',['data/parton_lumi_13TeV.json'])+`export const XS_LUMI=${JSON.stringify(lumi)};\n`);

const A=J('data/hepdata_atlas_ins3094414_fig10c.meta.json'),C=J('data/hepdata_cms_ins1764471.meta.json');
const N=C.tables.narrow_qq.columns,W=C.tables.spin1_qq_widths.columns;
const limits={
  atlas_tt:{paper:A.paper,doi:A.doi,raw_sha256:A.raw_sha256,hypothesis:A.signal_hypothesis,units:A.units,
    mass_TeV:A.columns.mass_TeV,observed_pb:A.columns.observed,expected_pb:A.columns.expected,theory_gKK30_pb:A.columns.theory_gKK_30pc},
  cms_dijet:{paper:C.paper,kinematics:C.kinematics,model_predictions:C.model_predictions,
    narrow:{doi:C.tables.narrow_qq.doi,raw_sha256:C.tables.narrow_qq.raw_sha256},spin1:{doi:C.tables.spin1_qq_widths.doi,raw_sha256:C.tables.spin1_qq_widths.raw_sha256},
    mass_GeV:N['Resonance mass [GeV]'],observed_narrow_pb:N['95% CL observed upper limits [pb]'],expected_narrow_pb:N['95% CL expected upper limits [pb]'],
    coloron_theory_pb:N['Axigluon/coloron cross section [pb]'],
    width_limits_pb:{'0.01':W['95% CL upper limits, 1% intrinsic width [pb]'],'0.10':W['95% CL upper limits, 10% intrinsic width [pb]'],
                     '0.30':W['95% CL upper limits, 30% intrinsic width [pb]'],'0.55':W['95% CL upper limits, 55% intrinsic width [pb]']}}};
const P=J('data/pdf_systematic_cteq6l1.json');
limits.pdf_systematic={sets:P.sets,ids:P.ids,channel:P.channel,M_GeV:P.rows.map(r=>r.M_GeV),ratio_NNPDF_over_CTEQ6L1:P.rows.map(r=>sig(r.ratio)),
  source:{file:'data/pdf_systematic_cteq6l1.json',sha256:sha('data/pdf_systematic_cteq6l1.json'),tool:'tools/pdf_systematic.py'}};
writeFileSync(resolve(root,'src/modules/xs_limits_reference.mjs'),head('Published LHC limits (HEPData, CC0) and the PDF systematic.',['data/hepdata_atlas_ins3094414_fig10c.meta.json','data/hepdata_cms_ins1764471.meta.json','data/pdf_systematic_cteq6l1.json'])+`export const XS_LIMITS=${JSON.stringify(limits)};\n`);

const B=J('data/rs_benchmark_cghnp2008.json');
writeFileSync(resolve(root,'src/modules/rf_benchmark_reference.mjs'),head('RS reference point of arXiv:0807.4937.',['data/rs_benchmark_cghnp2008.json'])+`export const RF_BENCHMARK=${JSON.stringify(B)};\n`);
const T=J('data/hepdata_cms_ins1901295.meta.json');
const tab=k=>{const t=T.tables[k];return {doi:t.doi,covariance_doi:t.covariance_doi,raw_sha256:t.raw_sha256,units:t.headers[1],
  bin_low_GeV:t.bin_low_GeV,bin_high_GeV:t.bin_high_GeV,value:t.value,stat:t.errors.stat,sys:t.errors.sys,covariance:t.covariance};};
const tt={paper:T.paper,record:T.record,license:T.license,level:T.level,abs:tab('abs'),norm:tab('norm'),
  source:{file:'data/hepdata_cms_ins1901295.meta.json',sha256:sha('data/hepdata_cms_ins1901295.meta.json'),tool:'tools/pin_hepdata_cms_ttbar.py'}};
writeFileSync(resolve(root,'src/modules/tt_cms_reference.mjs'),head('CMS parton-level m(tt̄) spectrum (HEPData, CC0).',['data/hepdata_cms_ins1901295.meta.json'])+`export const TT_CMS=${JSON.stringify(tt)};\n`);
const R=J('data/tt_spectrum_reference.json');
writeFileSync(resolve(root,'src/modules/tts_reference.mjs'),head('Independent tt̄ reference: Dirac traces, Combridge, LHAPDF directly.',['data/tt_spectrum_reference.json'])+
  `export const TTS_REFERENCE=${JSON.stringify({...R,source:{file:'data/tt_spectrum_reference.json',sha256:sha('data/tt_spectrum_reference.json'),tool:'tools/tt_spectrum_reference.py in tools/pdf.Dockerfile'}})};\n`);
for(const f of ['xs_lumi_reference.mjs','xs_limits_reference.mjs','rf_benchmark_reference.mjs','tt_cms_reference.mjs','tts_reference.mjs'])console.log(f,raw('src/modules/'+f).length,'bytes');
